---
AWSTemplateFormatVersion: "2010-09-09"
Description: Infrastructure for Jobaance static website with S3 and Route53
Parameters:
  DomainName:
    Type: String
    Description: Fully qualified domain name (example.com)
Mappings:
  RegionMap:
    us-east-1:
      S3WebsiteEndpoint: s3-website-us-east-1.amazonaws.com
      S3WebsiteHostedZoneId: Z3AQBSTGFYJSTF
    us-west-1:
      S3WebsiteEndpoint: s3-website-us-west-1.amazonaws.com
      S3WebsiteHostedZoneId: Z2F56UZL2M1ACD
    us-west-2:
      S3WebsiteEndpoint: s3-website-us-west-2.amazonaws.com
      S3WebsiteHostedZoneId: Z3BJ6K6RIION7M
    eu-west-1:
      S3WebsiteEndpoint: s3-website-eu-west-1.amazonaws.com
      S3WebsiteHostedZoneId: Z1BKCTXD74EZPE
Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SiteBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${SiteBucket.Arn}/*"
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${DomainName}."
      Name: !Sub "${DomainName}."
      Type: A
      AliasTarget:
        DNSName: !Sub
          - "${DomainName}.${S3WebsiteEndpoint}"
          - S3WebsiteEndpoint: !FindInMap
              - RegionMap
              - !Ref "AWS::Region"
              - S3WebsiteEndpoint
        HostedZoneId: !FindInMap
          - RegionMap
          - !Ref "AWS::Region"
          - S3WebsiteHostedZoneId
Outputs:
  WebsiteURL:
    Description: URL of the website
    Value: !Sub "http://${DomainName}"
